// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy4s39t3115_xA0ezgZcKyJgMkb1gXNWA',
    appId: '1:670485639767:web:7f327dd295d1d8f591a912',
    messagingSenderId: '670485639767',
    projectId: 'whisper-app-7fc7a',
    authDomain: 'whisper-app-7fc7a.firebaseapp.com',
    storageBucket: 'whisper-app-7fc7a.firebasestorage.app',
    measurementId: 'G-GNZMGSJSBB',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZsO6c8Yb8H6DO_HQvYZZpGdqO4AEfG_o',
    appId: '1:670485639767:ios:30c42d074d2d1c8b91a912',
    messagingSenderId: '670485639767',
    projectId: 'whisper-app-7fc7a',
    storageBucket: 'whisper-app-7fc7a.firebasestorage.app',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
